### ISSUE TITLE
A question for you...

### ISSUE THREAD

**Issue by gep13** [dcjulian29/choco-packages#1]
I just wanted to ask, when you say:

> The need for this collection of packages including ones that are otherwise available on the public feed are unfortunately due to the fact that I don't trust non-program authors to package the application nor do I agree with many of the "placement" and "defaults" that are provided by the authors in the public feed, not to mention several of the packages have severe bugs which are not the fault of chocolatey directly. So for me, I'll disable the "chocolatey" repository and use my personal repository.

What type of bugs exactly are you referring to?  Have you contacted the maintainers of the packages in question to see if these things can be corrected?  Also, with regard to not agreeing with where certain things are installed to, I think going forward with Chocolatey vNext, and the removal of version numbers from the chocolateyinstall\lib\package folder, I think this will get better.

In addition, we have started formalising the documentation around the use of [PackageParameters](https://github.com/chocolatey/choco/wiki/How-To-Parse-PackageParameters-Argument) so hopefully if there is a decision to be made in a package about where something is installed, they could be made available via a PackageParameter.

Would love to hear your thoughts on this.

Also, have you seen that we have enabled Package Moderation, where we are actively checking the contents of a Chocolatey Package and ensuring it installs correctly, before it makes it onto chocolatey.org?

**Comment by dcjulian29** [comment]
That was written a long time ago and I should really update it and “reduce the tone” as the current versions of the project have done a lot to reduce the issues I had when I originally wrote that.

Most of the bugs were things like files and/or settings getting overwritten or deleted, packages not installing due errors in their installer and not taking into account the differences between 32-bit and 64-bit OS environments. Upgrades were notorious... Everyone on the Internet is "opinionated" just like me and I got some nasty responses when I reached out to some maintainers if I got a response at all... I started with just a few "custom" packages and then started adding more and more that I customized for my environment. At some point, I just simply stopped using the public feed...

I'm very much looking forward to the next version of Choco and have been excited to see the pre-releases so far. I'm also looking forward to the upcoming OneGet "meta" package manager. I think removal of version numbers will allow easier upgrades especially for me since someone like me would have to constantly update my program launcher to handle version numbers in the directory name the way it currently works. I think that Package Parameters will go a long way to addressing some of my concerns but only if the package maintainers started using them. I’m actually looking to toward this for my Team City Agent package (that I haven’t created yet) in that I can specify the location of my Team City server without having to hard-code it or to assume what it would be…

I have noticed and appreciate the package moderation, but I think that the public chocolatey repository falls victim to the same problem as any other open package repository does. Just look at the Apple App Store or the Windows App Store for a large-scale example. How many fart apps do we need? Moderation doesn’t work if you set the bar low. It is not the fault of the package repository or the App Store, there is just a lot of crap out there. Package maintainer come and go and sometimes they go into disrepair and are neglected. At least if one of my packages is crap or causes me grief because I was stupid and didn’t take something into account, I can only blame myself. If I decide to stop maintaining the package, which I have as my taste in programs/tools change, I simply delete the package and move on. That is hard to do on a public feed… It is also hard to “transfer” the maintainer role of a package. Who decides if that package is stale, neglected, or if the maintainer is just taking a break?

Like I said above, my readme doesn’t reflect my opinion 100% so I’ll update it today... Thanks for bringing it to my attention.

**Comment by gep13** [comment]
Thanks for getting back to me!  All valid points, and some things that we can look to improve going forward.

With regard to your Team City Agent Package, have you seen this:

https://chocolatey.org/packages/TeamCityAgent

It allows you to specify the Server URL, and then downloads the Agent installation directly from that Server.

**Comment by dcjulian29** [comment]
I have seen this which gave me the idea as well as one for the "tray notifier".

**Comment by gep13** [comment]
:+1:
